//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paylocity_Code_Challenge.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitsCost
    {
        public int Id { get; set; }
        public string EmployeeBenefit { get; set; }
        public string DependentBenefit { get; set; }
    }
}
